import pandas as pd
from snakemake.utils import min_version

min_version("6.15.0")


#### config ####
configfile: "config/config.yaml"

#### load rules
include: "rules/common.smk"
include: "rules/call_variants.smk"


module dima:
    snakefile:
        github("solida-core/dima", path="workflow/Snakefile", tag="143abd3")
    config: config
    skip_validation: True

use rule * from dima as dima_*





rule all:
    input:
        rules.dima_all.input,
        expand(resolve_results_filepath(config.get("paths").get("results_dir"),
            "variant_calling/{sample.sample}.g.vcf.gz"
        ),
            sample=samples.reset_index().itertuples(),
        )
    default_target: True


